spring.application.name=api-aws

# server
# server.servlet.context-path=/webservice/api-aws
server.port=8080

# configure database
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true

#spring.jpa.open-in-view=false
#spring.jpa.properties.hibernate.enable_lazy_load_no_trans=true

# Dialeto (opcional nas versões atuais)
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# configure database
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://aula-aws-java-pleno.cl2cecsgk9sm.us-east-2.rds.amazonaws.com:3306/mysql?useSSL=true&requireSSL=true&verifyServerCertificate=false
spring.datasource.username=admin
spring.datasource.password={DB_PASSWORD}

# spring.datasource.hikari.connection-timeout=30000
# spring.datasource.hikari.minimum-idle=2
# spring.datasource.hikari.maximum-pool-size=4
# spring.datasource.hikari.idleTimeout=600000
# spring.datasource.hikari.maxLifetime=1200000
# spring.datasource.hikari.pool-name=ApiAwsPoolDev

# =========================================
# LOG DA APLICAÇÃO
# =========================================
logging.level.org.springframework=INFO
logging.level.root=INFO

# =========================================
# LOG DE SQL
# =========================================
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE
logging.level.org.hibernate.type.descriptor.sql=TRACE
# logging.level.com.zaxxer.hikari.HikariConfig=INFO
# logging.level.com.zaxxer.hikari=INFO
# logging.level.org.springframework.transaction=INFO

